apiVersion: v1
kind: Secret
metadata:
  name: kron-secrets
type: Opaque
data:
  DODO_WEBHOOK_KEY: "d2hzZWNfRk9DbjFUYlJDenBWOGU1eThvUHhPVUc5NW9Oc05UWjEK"
  NEXT_PUBLIC_CLERK_SECRET_KEY: "c2tfdGVzdF9FaTBMc0lnbTZyU0dCbkpuQmxHeVFvOEJTQWc4VlNueFExQWlqZnN0RmI="
  NEXT_PUBLIC_SUPABASE_ANON_KEY: "ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnBjM01pT2lKemRYQmhZbUZ6WlNJc0luSmxaaUk2SW5wa2QyaGtlbnB4WTJ0bVptWjJabTFsYW1SbUlpd2ljbTlzWlNJNkltRnViMjRpTENKcFlYUWlPakUzTlRFd09EazJNRGdzSW1WNGNDSTZNakEyTmpZMk5UWXdPSDAudzcteUtSd3J5S25xMEM0RDJERlI0cGt1SExhZ0lMQ2stVExSclNsOTRITQ=="