name: Buid & Push docker image

on:
  push:
    branches: ["main"]

env:
  Registry: ghcr.io
  ImageName: ${{github.repository}}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: checkout repository
      uses: actions/checkout@v4

    - name: Login to the container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{env.Registry}}
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: Extract metadata for docker image
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{env.Registry}}/${{env.ImageName}}
    
    - name: Build the docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{steps.meta.outputs.tags}}
        labels: ${{steps.meta.outputs.labels}}
        build-args: |
          DODO_WEBHOOK_KEY=${{ secrets.DODO_WEBHOOK_KEY }}
          NEXT_PUBLIC_CLERK_SECRET_KEY=${{ secrets.NEXT_PUBLIC_CLERK_SECRET_KEY }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure aws credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        aws-region: us-east-1

    - name: Update kube configure
      run: aws eks update-kubeconfig --name kron-cluster --region us-east-1

    - name: Deploy manifest
      run: kubectl apply -f k8s/